# General GitHub Repository Settings
repository:
  license: MIT

matlab_toolbox:
  namespace_name: mikestoolbox
  toolbox_name: Mikes Toolbox              
  author_name: Michael Wheelock                     
  author_email: michael@wheelockworks.com        
  author_company: wheelockworks
  toolbox_summary: This is a test of the toolbox template provided
  toolbox_description: |
    A test toolbox to learn how the MATLAB toolbox template may work for the AIDIF project.
    This repository will help familiarize with an ideal toolbox structure and help to clarify
    how script and function templates can be incorporated into the template.

  dependencies:
    - MATLAB
    - Signal Processing Toolbox

fileexchange:
  fex_url: None
